### ISSUE TITLE
README needs an update

### ISSUE THREAD

**Issue by lukebarnard1** [lukebarnard1/journal#64]
It still mentions custom CSS, which is no longer part of journal.

**Comment by hydeenoble** [comment]
Hi @lukebarnard1,

I would like to take this up, where is it supposed to be linked to??

**Comment by lukebarnard1** [comment]
Hey @hydeenoble, thanks for the offer!

Basically https://github.com/lukebarnard1/journal#style-modifications needs to say that style modifications can be done by editing `style.css` instead of `custom.css`.

**Comment by hydeenoble** [comment]
ok... great, I will make that quick fix then.
